version: '2'

services:
    php:
      user: "${UID}:${GID}"
      build: docker/php7fpm
      depends_on:
        - go
      expose:
        - 9000
      working_dir: /app
      volumes:
        - .:/app
        - ./docker/php7fpm/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini

    nginx:
      image: nginx:alpine
      depends_on:
        - php
      ports:
        - "80:80"
      volumes:
         - .:/app
         - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

    go:
      build: ./awale-go
      command: go run src/webserver/webserver.go
      expose:
          - 8080
      ports:
          - "8080:8080"
      volumes:
        - ./awale-go:/src
