# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    awale.baseUrl: "go:8080"

services:
    guzzle.client:
        class: GuzzleHttp\Client

    app.slack.client:
        class: AppBundle\Slack\SlackClient
        arguments:
          - "@guzzle.client"
          - "%slack_endpoint%"

    app.awale.client:
        class: AppBundle\Awale\AwaleClient
        arguments:
          - "@guzzle.client"
          - "%awale.baseUrl%"

    app.slack.controller:
        class: AppBundle\Slack\SlackController
        arguments: ["@app.slack.client", "@app.awale.client", "@app.awale.gameslack"]

    app.awale.gameslack:
        class: AppBundle\Awale\GameSlackFormatter
        arguments:
          - "@app.awale.boardimage"

    app.awale.boardimage:
        class: AppBundle\Awale\BoardImageConverter
        arguments:
          - "%url_images%"
