# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    awale.baseUrl: "http://localhost:2000"

services:
    guzzle.client:
        class: GuzzleHttp\Client

    app.slack.client:
        class: AppBundle\Slack\SlackClient
        arguments:
          - "@guzzle.client"
          - "%slack_endpoint%"

    app.awale.client:
        class: AppBundle\Awale\AwaleClient
        arguments:
          - "@guzzle.client"
          - "%awale.baseUrl%"

    app.slack.controller:
        class: AppBundle\Slack\SlackController
        arguments: ["@app.slack.client", "@app.awale.client", "@app.awale.slack_game_formatter"]

    app.awale.slack_game_formatter:
        class: AppBundle\Awale\GameSlackFormatter
        arguments:
          - "@app.awale.board_image_convert"

    app.awale.board_image_convert:
        class: AppBundle\Awale\BoardImageGenerate
        arguments:
          - "%assetsBaseUrl%"
