# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:
   app.slack.client:
      class: AppBundle\Slack\SlackClient
      arguments:
          - "%slack_endpoint%"

   app.awale.client:
      class: AppBundle\Awale\AwaleClient

   app.slack.controller:
       class: AppBundle\Slack\SlackController
       arguments: ["@app.slack.client", "@app.awale.client"]
